export const ACTIONS_TYPE = {
    ICREASE_SECOND_COUNTER: 'ICREASE_SECOND_COUNTER',
    DECREASE_SECOND_COUNTER: 'DECREASE_SECOND_COUNTER',

    GET_SHOP_DATA: 'GET_SHOP_DATA',
    GET_SINGLE_ITEM: 'GET_SINGLE_ITEM',

    GET_ALL_USERS: 'GET_ALL_USERS',
    POST_NEW_USER: 'POST_NEW_USER',
    DELETE_USER: 'DELETE_USER'
}